- README.md
- foundry.toml
- src/auth/NonPayable.huff
- src/auth/OnlyContract.huff
- test/auth/OnlyContract.t.sol
Introduces an `ONLY_CONTRACT` macro that reverts when `tx.origin == msg.sender`.
> **Warning**
> This is a naive check that the sender is a contract address and is generally seen as an anti-pattern.
> Additionally, this breaks contract interoperability and breaks once account abstraction is implemented.
> feat: OnlyContract Modifier Macro

- src/math/FixedPointMath.huff
- test/math/FixedPointMath.t.sol
- test/math/mocks/FixedPointMathWrappers.huff
Optimizes `FixedPointMath` macros.
*Manually retrieved Huff macro gas costs from the debugger- could've missed / added an op's cost here or there. Will do a more thorough diff later. Data collected post optimization of `mulDivDown` & `mulDivUp`.
> Optimize `FixedPointMath`

- src/utils/JumpTableUtil.huff
Noticed that I used the `mul` opcode in the `JumpTableUtil` while using the lib in the Whitenoise CTF, changed to `shl`.
> Small optimization to `JumpTableUtil`

- foundry.toml
- src/auth/Auth.huff
- src/auth/Owned.huff
- src/auth/RolesAuthority.huff
- src/math/Trigonometry.huff
- src/proxies/ERC1967Upgrade.huff
- src/tokens/ERC20.huff
- src/tokens/ERC4626.huff
- src/utils/MerkleDistributor.huff
- src/utils/SafeTransferLib.huff
- src/utils/TSOwnable.huff
- test/auth/Auth.t.sol
- test/auth/Owned.t.sol
- test/auth/RolesAuthority.t.sol
- test/auth/mocks/AuthWrappers.huff
- test/auth/mocks/OwnedWrappers.huff
- test/auth/mocks/RolesAuthorityWrappers.huff
- test/data-structures/mocks/HashmapWrappers.huff
- test/proxies/mocks/ClonesWrappers.huff
- test/proxies/mocks/ProxyWrappers.huff
- test/tokens/mocks/ERC20MintableWrappers.huff
- test/tokens/mocks/ERC20Wrappers.huff
- test/tokens/mocks/ERC4626Wrappers.huff
- test/tokens/mocks/ERC721Wrappers.huff
- test/utils/mocks/BitPackLibWrappers.huff
- test/utils/mocks/SSTORE2Wrappers.huff
- test/utils/mocks/TSOwnableWrappers.huff
> hotfix: V1 Nits

- src/utils/LibBit.huff
- test/utils/LibBit.t.sol
- test/utils/mocks/LibBitWrappers.huff
Updates macro names in `LibBit` in accordance w/ Solady's function name changes.
`MSB` -> `FLS`
`LSB` -> `FFS`
> update: `LibBit` macro names

- src/tokens/ERC20.huff
I believe before this fix if this ctrct were called with calldata == "" the jumpi would evaluate false and roll into ALLOWANCE() or maybe just die because of missing stack element?  not sure. either way i think it sb `jump`
> fix: teeny tiny bug

- src/utils/LibBit.huff
- test/utils/LibBit.t.sol
- test/utils/mocks/LibBitWrappers.huff
As mentioned [here](https://github.com/pentagonxyz/huffmate/pull/85#pullrequestreview-1161936525), the base branch is updated to `dev`.
Note: Running `forge fmt` is updating all the test files (54). I think it should be a separate PR..
cc: @clabby
> Add `isPowOf2()` to `LibBit`

- src/data-structures/Hashmap.huff
In the `concat the two keys` step of GET_SLOT_FROM_KEYS_2D (Hashmap.huff), one of the stack layout comments was missing `slot1` before that value is removed from the stack. Added it in the comment.
> Fix stack layout comment in GET_SLOT_FROM_KEYS_2D

- test/utils/TSOwnable.t.sol
Ownable tests were not passing locally because the huffConfig address wasn't the correct one.
This is because this function:
https://github.com/huff-language/foundry-huff/blob/eb9ea316389e8bd580f92908b8454399401d0316/src/HuffDeployer.sol#L10-L12
returns a new HuffConfig each it's called. For a long-term fix I would propose to apply the library to a config contract instead of creating one each time a function from the lib is called.
Here is a similar issue: https://github.com/huff-language/foundry-huff/pull/24
> Fix huffconfig address

- src/data-structures/Hashmap.huff
- test/data-structures/Hashmap.t.sol
- test/data-structures/mocks/HashmapWrappers.huff
* Add Hashmap 3D macros
* Add testing for those macros
* Add missing testing for 2D macros
* Remove 'view' type from store functions definitions in HashmapWrappers
> Add Hashmap slot+3keys (3D) macros

- src/utils/Ternary.huff
Old `TERNARY` macro:
```huff
// Input Stack: [condition, x, y]
// If the condition is false, jump and pop
iszero __Utils_Misc__ternaryNoSwap jumpi
swap1 // [y, x]
__Utils_Misc__ternaryNoSwap:
// condition ? [y, x] : [x, y]
pop // condition ? [x] : [y]
```
When the condition is true, the operations are:
`iszero push jumpi swap jumpdest pop` = 23 gas
When it's false:
`iszero push jumpi jumpdest pop` = 20 gas
If we use branchless logic we can get this down to 17 for both cases:
```huff
// Input Stack: [condition, x, y]
swap1           // [x, condition, y]
dup3            // [y, x, condition, y]
xor mul xor     // [((x ^ y) * condition) ^ y]
// Output Stack: [condition ? x : y]
```
`swap1 dup3 xor mul xor` = 17 gas
I don't think it's possible to do the same optimization for the inverse macro …
> Fix ternary tests and optimize TERNARY macro

- test/tokens/mocks/ERC20MintableWrappers.huff
Changing `no-match jumpi` to `no-match jump` in ERC20.huff function dispatcher leaves the shifted function sig on the stack for contracts inheriting it which can use it after the `no-match` JUMPDEST. This way, importing (wrapping) contracts only have to add:
```
0x00 calldataload 0xE0 shr
ERC20_MAIN()
```
to the start of their MAIN() macro then add their specific function below it rather than copying all of ERC20.huff dispatch macro.
> use ERC20_MAIN macro

- README.md
- src/utils/Pausable.huff
Renames some variables inside `pausable.huff`
> fix: pausable tidy

- src/tokens/ERC20.huff
According to the EIP decimals should returns a uint8; https://eips.ethereum.org/EIPS/eip-20#decimals
> fix: ERC20.decimals() signature to return uint8

- src/data-structures/Hashmap.huff
This changes the pattern of hashing for slots in `Hashmap.huff` to match that of how solidity lang handles mappings.
`GET_SLOT_FROM_KEYS()` function uses `sha3(slot . key)` against `sha3(key . slot)` used in solidity,
`GET_SLOT_FROM_KEYS_2D()` function uses `sha3(sha3(slot . key1) . key2)` against `sha3(key2 . sha3(key1 . slot)` used in solidity and 
`GET_SLOT_FROM_KEYS_3D()` function uses `sha3(key3 . sha3(key2 . sha3(slot . key1)))` against `sha3(key3 . sha3(key2 . sha3(key1 . slot)))` used in solidity.
> fix: hashmap.huff hashing pattern changed to solidity pattern

- README.md
Links and foundry installation 'pentagonxyz' changed to 'huff-language'. I should note that the mentioned hardhat/truffle installation does not work.
> Change pentagonxyz to huff-language in README.md

- src/proxies/ERC1967Upgrade.huff
> opti: ERC1967Upgrade, remove double iszero before jumpi

- src/tokens/ERC4626.huff
Removes unnecessary `iszero` in `ERC4626.huff` used to check if stack variable is different from 0 before a `jumpi`. 
Using stack variable directly is sufficient.
Allows to save 2 instructions each time those macros are called.
Part of #117
> opti: ERC4626, remove double iszero before jumpi

- test/tokens/ERC20.t.sol
Fixes test caused by missing `startPrank` clause
> fix: erc20-test

- src/utils/SafeTransferLib.huff
save 6 gas/mana on safeTransferLib (safeTransfer, safeTransferFrom, safeApprove) calls by using `<mem_ptr>` as return data offset rather than `<mem_ptr> + 0x1c`
> save some gas/mana on `safe` lib calls

- src/tokens/ERC1155.huff
- src/tokens/ERC721.huff
- src/utils/Calls.huff
- src/utils/ERC20Transfer.huff
- src/utils/Refunded.huff
- src/utils/SSTORE2.huff
- test/tokens/mocks/ERC4626Wrappers.huff
- test/utils/mocks/CallWrappers.huff
- test/utils/mocks/EthersWrappers.huff
using `iszero` twice before `jumpi` is unnecessary as `jumpi` is compares between non-zero and zero (if !0 -> true), and not between 1 and 0 (if 1 -> true, else -> false).
https://www.evm.codes/#57?fork=shanghai
> Optimization: Removed double `iszero` before `jumpi`
